//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchPr_Glushkov_523
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public string Reason { get; set; }
        public int AdminID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
